# frozen_string_literal: true

require "erb"
require "yaml"
require "active_record"
require "active_record/tasks/database_tasks"

# Real-PostgreSQL setup for the ActiveRecord specs, driven by the same
# ActiveRecord machinery a Rails app uses: connection settings from
# spec/db/database.yml, the schema from spec/db/schema.rb (generated by
# `rake db:migrate` from spec/db/migrate), seeds from spec/db/seeds.rb.
# Requiring this file configures ActiveRecord::Tasks::DatabaseTasks and
# touches nothing else: call .setup from a spec hook.
module DeckardTestDatabase
  DB_DIR = File.expand_path("../db", __dir__)
  SCHEMA = File.join(DB_DIR, "schema.rb")
  SEEDS = File.join(DB_DIR, "seeds.rb")
  ENV_NAME = "test"

  Tasks = ActiveRecord::Tasks::DatabaseTasks
  Tasks.env = ENV_NAME
  Tasks.root = File.expand_path("../..", __dir__)
  Tasks.db_dir = DB_DIR
  Tasks.migrations_paths = [File.join(DB_DIR, "migrate")]
  ActiveRecord::Migrator.migrations_paths = Tasks.migrations_paths
  Tasks.database_configuration = YAML.safe_load(ERB.new(File.read(File.join(DB_DIR, "database.yml"))).result)
  Tasks.seed_loader = Object.new.tap do |loader|
    def loader.load_seed
      load DeckardTestDatabase::SEEDS
    end
  end
  ActiveRecord::Base.configurations = Tasks.database_configuration

  def self.primary_config
    ActiveRecord::Base.configurations.configs_for(env_name: ENV_NAME, name: "primary")
  end

  def self.destination_config
    ActiveRecord::Base.configurations.configs_for(env_name: ENV_NAME, name: "destination")
  end

  class SourceRecord < ActiveRecord::Base
    self.abstract_class = true
  end

  class DestinationRecord < ActiveRecord::Base
    self.abstract_class = true
  end

  # Bring the primary database up to spec/db/schema.rb, verify the server
  # runs PostgreSQL 18 (matching the e2e harness), and connect. Memoized
  # across calls; connection and setup failures propagate.
  def self.setup
    return if @setup

    ActiveRecord::Base.establish_connection(primary_config)
    prepare(primary_config)
    check_server_version(primary_config)
    truncate # rows left by `rake db:seed` must not leak into the examples
    configure_encryption
    SourceRecord.establish_connection(primary_config)
    @setup = true
  end

  def self.setup_destination
    return if @destination_setup

    prepare(destination_config)
    DestinationRecord.establish_connection(destination_config)
    @destination_setup = true
  ensure
    ActiveRecord::Base.establish_connection(primary_config)
  end

  def self.with_destination
    ActiveRecord::Base.establish_connection(destination_config)
    yield
  ensure
    ActiveRecord::Base.establish_connection(primary_config)
  end

  def self.truncate
    connection = ActiveRecord::Base.connection
    tables = connection.tables - %w[schema_migrations ar_internal_metadata]
    connection.execute("TRUNCATE #{tables.join(", ")} RESTART IDENTITY CASCADE")
  end

  # The same steps as Rails' `db:test:prepare`: create the database when it
  # is missing, and reload schema.rb whenever the loaded schema's recorded
  # digest no longer matches the file.
  def self.prepare(db_config)
    up_to_date = begin
      Tasks.schema_up_to_date?(db_config, :ruby, SCHEMA)
    rescue ActiveRecord::NoDatabaseError
      Tasks.create(db_config)
      false
    end
    return if up_to_date

    Tasks.with_temporary_pool_for_each(env: ENV_NAME, name: db_config.name) do
      Tasks.purge(db_config)
      Tasks.load_schema(db_config, :ruby, SCHEMA)
    end
  end
  private_class_method :prepare

  def self.check_server_version(db_config)
    version = ActiveRecord::Base.connection.select_value("SHOW server_version")
    unless version.start_with?("18.")
      raise "deckard specs must run against PostgreSQL 18 to match the e2e harness; " \
        "#{db_config.database} is running #{version}"
    end
  end
  private_class_method :check_server_version

  def self.configure_encryption
    ActiveRecord::Encryption.configure(
      primary_key: "deckard-test-primary-key",
      deterministic_key: "deckard-test-deterministic-key",
      key_derivation_salt: "deckard-test-salt"
    )
  end
end
