module Deckard
  VERSION: String

  class ModelConfig
    attr_reader scalar_references: Hash[Symbol, untyped]

    def scalar_reference: (Symbol | String attribute, to: untyped) -> untyped
                        | (Symbol | String attribute) { (untyped, untyped) -> untyped } -> untyped
  end
end
